apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnmpb1001-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnmpb1001-tenant-component
    app.kubernetes.io/part-of: loadnmpb1001-tenant-app
  name: loadnmpb1001-tenant-component
  namespace: loadnmpb1001-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnmpb1001-tenant-component
    weight: null
status: {}
