apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnmpb1001-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnmpb1001-tenant-component
    app.kubernetes.io/part-of: loadnmpb1001-tenant-app
  name: loadnmpb1001-tenant-component
  namespace: loadnmpb1001-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadnmpb1001-tenant-component
status:
  loadBalancer: {}
